version: "3.8"

#Setting MariaDB in Container
services:
  pgdbtest:
    image: ankane/pgvector:latest
    container_name: pgvectortest
    environment:
      POSTGRES_DB: springai
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user1234
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgdb:
    image: ankane/pgvector:latest
    container_name: pgvector
    environment:
      POSTGRES_DB: springai
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  app:
    build: ../basic
    ports:
      - "8081:8081"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/springai
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user1234

volumes:
  pgdata: