version: "3.8"

#Setting MariaDB in Container
services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: springai
      MARIADB_USER: user
      MARIADB_PASSWORD: user1234
    ports:
      - "3308:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  mariadbtest:
    image: mariadb:11
    container_name: mariadbtest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: springai
      MARIADB_USER: user
      MARIADB_PASSWORD: user1234
    ports:
      - "3309:3306"
  app:
    build: ../basic
    ports:
      - "8081:8081"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/springai
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user1234

volumes:
  mariadb-data: